// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PatchOptions controls the optional patching features of the MITM proxy.
 * Zero value disables all patching; callers should use DefaultPatchOptions()
 * to get the recommended defaults.
 */
export class PatchOptions {
    /**
     * RSAPatch enables replacement of RSA public key values in JSON/text responses.
     */
    "rsaPatch": boolean;

    /**
     * RSAKey overrides the injected RSA key. Empty → DefaultRSAKey.
     */
    "rsaKey": string;

    /**
     * WebRedirect enables URL rewriting in text/html/json/js responses.
     */
    "webRedirect": boolean;

    /**
     * WebHosts is a comma- or newline-separated list of exact hostnames whose
     * URLs are rewritten. Empty → DefaultWebHosts.
     */
    "webHosts": string;

    /** Creates a new PatchOptions instance. */
    constructor($$source: Partial<PatchOptions> = {}) {
        if (!("rsaPatch" in $$source)) {
            this["rsaPatch"] = false;
        }
        if (!("rsaKey" in $$source)) {
            this["rsaKey"] = "";
        }
        if (!("webRedirect" in $$source)) {
            this["webRedirect"] = false;
        }
        if (!("webHosts" in $$source)) {
            this["webHosts"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PatchOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): PatchOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PatchOptions($$parsedSource as Partial<PatchOptions>);
    }
}
