// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function DirExists(path) {
    return $Call.ByID(1772289644, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(path) {
    return $Call.ByID(1782610747, path);
}

/**
 * @param {string} archivePath
 * @param {string} fileInside
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function FileExistsInZip(archivePath, fileInside) {
    return $Call.ByID(2509699047, archivePath, fileInside);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetDir(path) {
    return $Call.ByID(1744445742, path);
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<string>}
 */
export function Join(...paths) {
    return $Call.ByID(2460588289, paths);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function OpenFolder(path) {
    return $Call.ByID(1635714001, path);
}

/**
 * @param {string} filter
 * @returns {$CancellablePromise<string>}
 */
export function PickFile(filter) {
    return $Call.ByID(3756474934, filter);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PickFolder() {
    return $Call.ByID(3654471460);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFile(path) {
    return $Call.ByID(3206735043, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function StartApp(path) {
    return $Call.ByID(1267568402, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function StartWithConsole(path) {
    return $Call.ByID(3249271428, path);
}
