// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HandbookService fetches the GM handbook from a March7thHoney server and
 * answers id/name lookups locally. The big text is kept here (cached per
 * server+language) so the UI only ever receives the matching entries.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Languages returns the handbook languages available on the server.
 */
export function Languages(serverURL: string): $CancellablePromise<[boolean, string[], string]> {
    return $Call.ByID(3524153679, serverURL).then(($result: any) => {
        $result[1] = $$createType0($result[1]);
        return $result;
    });
}

/**
 * Search fetches (and caches) the handbook for a language and returns every line
 * containing the query (case-insensitive) — a plain full-text search over the
 * whole handbook: commands, items, ids, names, everything.
 */
export function Search(serverURL: string, lang: string, query: string): $CancellablePromise<[boolean, string[], string]> {
    return $Call.ByID(147183680, serverURL, lang, query).then(($result: any) => {
        $result[1] = $$createType0($result[1]);
        return $result;
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
