// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CloseApp() {
    return $Call.ByID(3422460836);
}

/**
 * @param {number} timeout
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CloseAppAfterTimeout(timeout) {
    return $Call.ByID(1705931481, timeout);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function GetCurrentLauncherVersion() {
    return $Call.ByID(3575133982);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function HideApp() {
    return $Call.ByID(88003266);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function MaximizeApp() {
    return $Call.ByID(1257306588);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function MinimizeApp() {
    return $Call.ByID(3434614194);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function RestoreApp() {
    return $Call.ByID(3115625834);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function OpenURL(url) {
    return $Call.ByID(1592090092, url);
}
