// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * DownloadPatchProgress fetches the region-specific patch DLL asset for the
 * given version into constant.PatchStorageUrl, emitting "download:patch"
 * events as it streams.
 * 
 * region must be "os" or "cn"; anything else is treated as OS.
 * @param {string} region
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DownloadPatchProgress(region, version) {
    return $Call.ByID(703911776, region, version);
}

/**
 * @param {string} source
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DownloadProxyProgress(source, version) {
    return $Call.ByID(3559275334, source, version);
}

/**
 * @param {string} source
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DownloadServerProgress(source, version) {
    return $Call.ByID(1954767259, source, version);
}

/**
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestLauncherVersion() {
    return $Call.ByID(262637602);
}

/**
 * GetLatestPatchVersion returns the newest tag of the March7thHoney patch DLL
 * from its configured GitHub release feed. The response schema matches Gitea,
 * so the rest of the download pipeline is unchanged.
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestPatchVersion() {
    return $Call.ByID(2984284252);
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestProxyVersion(source) {
    return $Call.ByID(289488362, source);
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestServerVersion(source) {
    return $Call.ByID(2918980975, source);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnzipServer() {
    return $Call.ByID(1126363284);
}

/**
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function UpdateLauncherProgress(version) {
    return $Call.ByID(97272861, version);
}
