// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function DirExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(160707185, path);
}

export function FileExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(3297030196, path);
}

export function FileExistsInZip(archivePath: string, fileInside: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3061100906, archivePath, fileInside);
}

export function GetDir(path: string): $CancellablePromise<string> {
    return $Call.ByID(607772389, path);
}

export function GetGameVersion(gamePath: string): $CancellablePromise<string> {
    return $Call.ByID(2374017048, gamePath);
}

export function IsGenshinServerRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1264053998);
}

export function Join(...paths: string[]): $CancellablePromise<string> {
    return $Call.ByID(2891580430, paths);
}

export function OpenFolder(path: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3061305682, path);
}

export function PickFile(filter: string): $CancellablePromise<string> {
    return $Call.ByID(1095914605, filter);
}

export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(1421210103);
}

export function RemoveFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(572845152, path);
}

export function StartApp(path: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(870455593, path);
}

export function StartGenshinGame(yuanShenPath: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2373717338, yuanShenPath);
}

export function StartGenshinServer(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3170868339);
}

export function StopGenshinServer(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2226560723);
}
