// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function DirExists(path) {
    return $Call.ByID(160707185, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(path) {
    return $Call.ByID(3297030196, path);
}

/**
 * @param {string} archivePath
 * @param {string} fileInside
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function FileExistsInZip(archivePath, fileInside) {
    return $Call.ByID(3061100906, archivePath, fileInside);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function GetDir(path) {
    return $Call.ByID(607772389, path);
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<string>}
 */
export function Join(...paths) {
    return $Call.ByID(2891580430, paths);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function OpenFolder(path) {
    return $Call.ByID(3061305682, path);
}

/**
 * @param {string} filter
 * @returns {$CancellablePromise<string>}
 */
export function PickFile(filter) {
    return $Call.ByID(1095914605, filter);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function PickFolder() {
    return $Call.ByID(1421210103);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFile(path) {
    return $Call.ByID(572845152, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function StartApp(path) {
    return $Call.ByID(870455593, path);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function StartWithConsole(path) {
    return $Call.ByID(3720428927, path);
}
