// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Start installs the MITM proxy, sets the system proxy, launches gamePath,
 * and returns immediately. Returns (true, "") on success or (false, errMsg).
 *
 * targetURL is the private-server base URL (e.g. "https://march7th.hoyotoon.com").
 * An empty string uses the built-in default.
 * @param {string} gamePath
 * @param {string} targetURL
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function Start(gamePath, targetURL) {
    return $Call.ByID(3347991480, gamePath, targetURL);
}
