// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * DetectRegion inspects gameDir/BinaryVersion.bytes to figure out whether the
 * installed StarRail client is the OS (global / HoYoPlay) build or the CN
 * (国服 / miHoYo Launcher) build. Returns one of "os", "cn", or "" when the
 * region can't be determined — in that case the frontend should prompt the
 * user to pick a region manually.
 * 
 * Region detection is conservative: we only return "os"/"cn" when the
 * BinaryVersion name contains the matching marker. Anything else (file
 * missing, parse error, unrecognised name) returns "".
 * @param {string} gameDir
 * @returns {$CancellablePromise<string>}
 */
export function DetectRegion(gameDir) {
    return $Call.ByID(821696099, gameDir);
}

/**
 * Start launches gamePath suspended, injects dllPath, and resumes the main
 * thread. Returns (ok, errMessage). Emits "game:exit" via the Wails event bus
 * when the patched game process terminates, matching the convention used by
 * FSService.StartApp.
 * @param {string} gamePath
 * @param {string} dllPath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function Start(gamePath, dllPath) {
    return $Call.ByID(3347991480, gamePath, dllPath);
}
