// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * March7thHoneyService is constructed via New so the embedded CyreneHook.dll
 * bytes can be supplied from main.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as patchproxy$0 from "../../pkg/patch-proxy/models.js";

/**
 * IsLocalServerRunning reports whether the local server is up.
 */
export function IsLocalServerRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(166262603);
}

/**
 * OpenLocalServerFolder opens the selected local-server folder.
 */
export function OpenLocalServerFolder(mode: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2613507552, mode);
}

/**
 * Start launches gamePath with the local proxy + CyreneHook injection.
 * 
 * targetURL is the selected channel's server base URL (e.g. "https://server.march7th.cc").
 * An empty string uses constant.DefaultPatchTargetURL.
 * 
 * preferredPort is the loopback port the proxy tries to bind. 0 (or an
 * unavailable port) falls back to a random free port.
 * 
 * Returns (true, "") on success, (false, errMsg) on failure.
 */
export function Start(gamePath: string, targetURL: string, preferredPort: number, opts: patchproxy$0.PatchOptions): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3347991480, gamePath, targetURL, preferredPort, opts);
}

/**
 * StartLocalServer launches the selected local server ("test" | "prod") in its
 * own console. A server already listening on the local port counts as started.
 */
export function StartLocalServer(mode: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(720074128, mode);
}
