// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * NewsItem is the unified shape returned for all news sources.
 */
export class NewsItem {
    /**
     * Creates a new NewsItem instance.
     * @param {Partial<NewsItem>} [$$source = {}] - The source object to create the NewsItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("intro" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["intro"] = "";
        }
        if (!("image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["image"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("time" in $$source)) {
            /**
             * formatted YYYY-MM-DD
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * unix seconds, for sorting
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * "notice" / "event" / "info" / "" (server)
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewsItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NewsItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewsItem(/** @type {Partial<NewsItem>} */($$parsedSource));
    }
}
