// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Fetch official Star Rail launcher content (banners + posts).
 * Returns all 3 types (notice/event/info) in one call; frontend filters by NewsItem.type.
 *
 * @param {string} lang
 * @returns {$CancellablePromise<[boolean, Array<{id:string,title:string,intro:string,image:string,url:string,time:string,timestamp:number,type:string}>, string]>}
 */
export function GetOfficialNews(lang) {
    return $Call.ByID(2016417425, lang);
}

/**
 * Fetch the server announcements from AnnouncementUrl.
 *
 * @returns {$CancellablePromise<[boolean, Array<{id:string,title:string,intro:string,image:string,url:string,time:string,timestamp:number,type:string}>, string]>}
 */
export function GetCustomNews() {
    return $Call.ByID(826433463);
}
