// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetLanguage(path: string): $CancellablePromise<[boolean, string, string, string]> {
    return $Call.ByID(1449298450, path);
}

export function SetLanguage(path: string, text: string, voice: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(4157307294, path, text, voice);
}
