// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} source
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DownloadProxyProgress(source, version) {
    return $Call.ByID(144810991, source, version);
}

/**
 * @param {string} source
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DownloadServerProgress(source, version) {
    return $Call.ByID(779132168, source, version);
}

/**
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestLauncherVersion() {
    return $Call.ByID(391023589);
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestProxyVersion(source) {
    return $Call.ByID(2017476991, source);
}

/**
 * @param {string} source
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function GetLatestServerVersion(source) {
    return $Call.ByID(1666694076, source);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnzipServer() {
    return $Call.ByID(1616992225);
}

/**
 * @param {string} version
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function UpdateLauncherProgress(version) {
    return $Call.ByID(768035426, version);
}
