// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function DownloadProxyProgress(source: string, version: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(144810991, source, version);
}

export function DownloadServerProgress(source: string, version: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(779132168, source, version);
}

export function GetLatestLauncherVersion(): $CancellablePromise<[boolean, string, string]> {
    return $Call.ByID(391023589);
}

export function GetLatestProxyVersion(source: string): $CancellablePromise<[boolean, string, string]> {
    return $Call.ByID(2017476991, source);
}

export function GetLatestServerVersion(source: string): $CancellablePromise<[boolean, string, string]> {
    return $Call.ByID(1666694076, source);
}

export function UnzipServer(): $CancellablePromise<void> {
    return $Call.ByID(1616992225);
}

export function UpdateLauncherProgress(version: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(768035426, version);
}
