// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CloseApp(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(4287907331);
}

export function CloseAppAfterTimeout(timeout: number): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3736652886, timeout);
}

export function GetCurrentLauncherVersion(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2767927275);
}

export function HideApp(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2658494055);
}

export function MaximizeApp(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2363462957);
}

export function MinimizeApp(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(1985260791);
}

export function OpenURL(url: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(1132232877, url);
}

export function RestoreApp(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2717046005);
}
