// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CloseApp() {
    return $Call.ByID(4287907331);
}

/**
 * @param {number} timeout
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CloseAppAfterTimeout(timeout) {
    return $Call.ByID(3736652886, timeout);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function GetCurrentLauncherVersion() {
    return $Call.ByID(2767927275);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function HideApp() {
    return $Call.ByID(2658494055);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function MaximizeApp() {
    return $Call.ByID(2363462957);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function MinimizeApp() {
    return $Call.ByID(1985260791);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function OpenURL(url) {
    return $Call.ByID(1132232877, url);
}

/**
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function RestoreApp() {
    return $Call.ByID(2717046005);
}
