/// <reference types="vite/client" />

interface ImportMetaEnv {
    readonly VITE_FEATURE_NEWS?: string
    readonly VITE_FEATURE_LANGUAGE_TOOLS?: string
    readonly VITE_FEATURE_DIFF_TOOLS?: string
    readonly VITE_FEATURE_ANALYSIS?: string
    readonly VITE_FEATURE_SR_TOOLS?: string
    readonly VITE_FEATURE_CONSOLE?: string
    readonly VITE_FEATURE_HOW_TO?: string
    readonly VITE_FEATURE_ABOUT?: string
    readonly VITE_FEATURE_ACCOUNT?: string
    readonly VITE_FEATURE_EXTERNAL_TOOL_LINKS?: string
    readonly VITE_FEATURE_DISCORD_LINK?: string
    readonly VITE_FEATURE_HOME_LINK_FIREFLY_ANALYSIS?: string
    readonly VITE_FEATURE_HOME_LINK_FIREFLY_SRTOOLS?: string
    readonly VITE_FEATURE_HOME_LINK_AMAZING_SRTOOLS?: string
    readonly VITE_FEATURE_HOME_LINK_DISCORD?: string
    readonly VITE_FEATURE_HOME_LINK_HOW_TO?: string
    readonly VITE_FEATURE_BACKGROUND_SELECTOR?: string
    readonly VITE_FEATURE_GAME_PROFILE_SWITCHER?: string
    readonly VITE_LAUNCHER_APP_NAME?: string
    readonly VITE_LAUNCHER_APP_SUBTITLE?: string
    readonly VITE_LAUNCHER_SUBTITLE_MODE?: string
    readonly VITE_LAUNCHER_GAME_VERSION_SUBTITLE_PREFIX?: string
    readonly VITE_LAUNCHER_GAME_VERSION_UNKNOWN_SUBTITLE?: string
    readonly VITE_LAUNCHER_GAME_VERSION_MISSING_SUBTITLE?: string
    readonly VITE_LAUNCHER_APP_ICON?: string
    readonly VITE_LAUNCHER_BRANDED_CHROME?: string
    readonly VITE_LAUNCHER_PROJECT_AUTHOR?: string
    readonly VITE_LAUNCHER_PROJECT_REPO_URL?: string
    readonly VITE_LAUNCHER_DISCORD_URL?: string
    readonly VITE_LAUNCHER_DEFAULT_PATCH_URL?: string
    readonly VITE_LAUNCHER_DEFAULT_PATCH_SERVER_PORT?: string
    readonly VITE_LAUNCHER_GRADIENT_FROM?: string
    readonly VITE_LAUNCHER_GRADIENT_VIA?: string
    readonly VITE_LAUNCHER_GRADIENT_TO?: string
    readonly VITE_LAUNCHER_THEME_PRIMARY?: string
    readonly VITE_LAUNCHER_THEME_SECONDARY?: string
    readonly VITE_LAUNCHER_THEME_ACCENT?: string
    readonly VITE_LAUNCHER_BRAND_TEXT_COLOR?: string
    readonly VITE_LAUNCHER_MUTED_TEXT_COLOR?: string
    readonly VITE_LAUNCHER_THEME_SOFT_BACKGROUND_COLOR?: string
    readonly VITE_LAUNCHER_THEME_SOFT_BACKGROUND_STRONG_COLOR?: string
    readonly VITE_LAUNCHER_THEME_SOFT_BORDER_COLOR?: string
    readonly VITE_LAUNCHER_THEME_SOFT_SHADOW_COLOR?: string
    readonly VITE_LAUNCHER_THEME_OVERLAY_BACKGROUND_COLOR?: string
    readonly VITE_LAUNCHER_PANEL_BACKGROUND_COLOR?: string
    readonly VITE_LAUNCHER_PANEL_BORDER_COLOR?: string
    readonly VITE_LAUNCHER_PANEL_TEXT_COLOR?: string
    readonly VITE_LAUNCHER_PANEL_HOVER_BACKGROUND_COLOR?: string
    readonly VITE_LAUNCHER_PANEL_HOVER_TEXT_COLOR?: string
    readonly VITE_LAUNCHER_THEME_BASE_100_COLOR?: string
    readonly VITE_LAUNCHER_THEME_BASE_200_COLOR?: string
    readonly VITE_LAUNCHER_THEME_BASE_300_COLOR?: string
    readonly VITE_LAUNCHER_THEME_BASE_CONTENT_COLOR?: string
    readonly VITE_LAUNCHER_THEME_SUCCESS_COLOR?: string
    readonly VITE_LAUNCHER_THEME_WARNING_COLOR?: string
    readonly VITE_LAUNCHER_THEME_ERROR_COLOR?: string
    readonly VITE_LAUNCHER_DEFAULT_BACKGROUND?: string
    readonly VITE_LAUNCHER_STARRAIL_BACKGROUND?: string
    readonly VITE_LAUNCHER_GENSHIN_BACKGROUND?: string
    readonly VITE_LAUNCHER_BACKGROUND_OPTIONS?: string
}
