// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelLogin(): $CancellablePromise<void> {
    return $Call.ByID(3770370519);
}

/**
 * DeviceID exposes the machine fingerprint so the local server presents the same device identity to the backend.
 */
export function DeviceID(): $CancellablePromise<string> {
    return $Call.ByID(1805274335);
}

/**
 * GetProfile validates the stored token against the website and returns the
 * account profile. Called on app start to restore the session.
 */
export function GetProfile(): $CancellablePromise<[boolean, $models.Profile, string]> {
    return $Call.ByID(941664977).then(($result: any) => {
        $result[1] = $$createType0($result[1]);
        return $result;
    });
}

/**
 * GetWebBaseURL lets the frontend build website links (profile page etc.).
 */
export function GetWebBaseURL(): $CancellablePromise<string> {
    return $Call.ByID(3317106280);
}

export function IsLoggedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(2827752849);
}

export function Logout(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2486771742);
}

/**
 * ServerToken returns the persisted launcher token for a launcher-managed local March7thHoney server.
 */
export function ServerToken(): $CancellablePromise<string> {
    return $Call.ByID(2409911808);
}

/**
 * StartLogin begins the device flow and returns once the browser is opened.
 * The result arrives via the "account:login:success" / "account:login:failed"
 * events.
 */
export function StartLogin(): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3599785977);
}

// Private type creation functions
const $$createType0 = $models.Profile.createFrom;
