// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LauncherConfig is the website's client-side policy. It is served
 * unauthenticated at /api/launcher/config because the login gate needs it
 * before anybody is signed in.
 */
export class LauncherConfig {
    /**
     * SkipLoginEnabled reports whether the gate may offer "continue without
     * signing in". Admins turn it off to make an account mandatory.
     */
    "skip_login_enabled": boolean;

    /** Creates a new LauncherConfig instance. */
    constructor($$source: Partial<LauncherConfig> = {}) {
        if (!("skip_login_enabled" in $$source)) {
            this["skip_login_enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LauncherConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LauncherConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LauncherConfig($$parsedSource as Partial<LauncherConfig>);
    }
}

export class Profile {
    "id": string;
    "name": string;
    "image": string;
    "role": string;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile($$parsedSource as Partial<Profile>);
    }
}
