// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Profile {
    "id": string;
    "name": string;
    "image": string;
    "role": string;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile($$parsedSource as Partial<Profile>);
    }
}
