// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * NewsItem is the unified shape returned for all news sources.
 */
export class NewsItem {
    "id": string;
    "title": string;
    "intro": string;
    "image": string;
    "url": string;

    /**
     * formatted YYYY-MM-DD
     */
    "time": string;

    /**
     * unix seconds, for sorting
     */
    "timestamp": number;

    /**
     * "notice" / "event" / "info" / "" (server)
     */
    "type": string;

    /**
     * server announcements only
     */
    "pinned": boolean;

    /** Creates a new NewsItem instance. */
    constructor($$source: Partial<NewsItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("intro" in $$source)) {
            this["intro"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewsItem instance from a string or object.
     */
    static createFrom($$source: any = {}): NewsItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewsItem($$parsedSource as Partial<NewsItem>);
    }
}
