// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetCustomNews fetches server announcements from the Cyrene website API
 * (constant.AnnouncementUrl), which returns a plain []NewsItem array with
 * pinned posts first.
 */
export function GetCustomNews(): $CancellablePromise<[boolean, $models.NewsItem[], string]> {
    return $Call.ByID(3670222014).then(($result: any) => {
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

/**
 * GetOfficialNews fetches the HoYoPlay content for HSR (banners + 3-type posts)
 * in a single HTTP request. Frontend filters posts by type for each tab.
 */
export function GetOfficialNews(lang: string): $CancellablePromise<[boolean, $models.NewsItem[], string]> {
    return $Call.ByID(1638005996, lang).then(($result: any) => {
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

// Private type creation functions
const $$createType0 = $models.NewsItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
