// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CheckTypeHDiff(patchPath: string): $CancellablePromise<[boolean, string, string]> {
    return $Call.ByID(2225384349, patchPath);
}

export function CutData(gamePath: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(4128606402, gamePath);
}

export function DataExtract(gamePath: string, patchPath: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(3063526727, gamePath, patchPath);
}

export function DeleteFiles(gamePath: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2090475352, gamePath);
}

export function HDiffPatchData(gamePath: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2478195521, gamePath);
}

export function LDiffPatchData(gamePath: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(1781105813, gamePath);
}

export function VersionValidate(gamePath: string, patchPath: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(364961568, gamePath, patchPath);
}
