// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function CheckTypeHDiff(patchPath) {
    return $Call.ByID(2225384349, patchPath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CutData(gamePath) {
    return $Call.ByID(4128606402, gamePath);
}

/**
 * @param {string} gamePath
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DataExtract(gamePath, patchPath) {
    return $Call.ByID(3063526727, gamePath, patchPath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DeleteFiles(gamePath) {
    return $Call.ByID(2090475352, gamePath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function HDiffPatchData(gamePath) {
    return $Call.ByID(2478195521, gamePath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function LDiffPatchData(gamePath) {
    return $Call.ByID(1781105813, gamePath);
}

/**
 * @param {string} gamePath
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function VersionValidate(gamePath, patchPath) {
    return $Call.ByID(364961568, gamePath, patchPath);
}
