// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string, string]>}
 */
export function CheckTypeHDiff(patchPath) {
    return $Call.ByID(3717449114, patchPath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function CutData(gamePath) {
    return $Call.ByID(2019290107, gamePath);
}

/**
 * @param {string} gamePath
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DataExtract(gamePath, patchPath) {
    return $Call.ByID(2161622254, gamePath, patchPath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function DeleteFiles(gamePath) {
    return $Call.ByID(1103091613, gamePath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function HDiffPatchData(gamePath) {
    return $Call.ByID(3944051994, gamePath);
}

/**
 * @param {string} gamePath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function LDiffPatchData(gamePath) {
    return $Call.ByID(360123238, gamePath);
}

/**
 * @param {string} gamePath
 * @param {string} patchPath
 * @returns {$CancellablePromise<[boolean, string]>}
 */
export function VersionValidate(gamePath, patchPath) {
    return $Call.ByID(2105077257, gamePath, patchPath);
}
