// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsoleService talks to a March7thHoney server's /console/* endpoints so the
 * launcher can run in-game commands and self-reset without opening the chat.
 * Authentication is per-player (UID + password), same as in-game chat.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Execute POSTs a command to the server and returns (ok, output, error).
 * An empty command performs a credential check only (used by "Connect").
 */
export function Execute(serverURL: string, uid: number, password: string, command: string): $CancellablePromise<[boolean, string, string]> {
    return $Call.ByID(3077864999, serverURL, uid, password, command);
}

/**
 * SelfReset wipes the authenticated player's own gameplay data (account kept).
 * Destructive — the caller must confirm with the user first.
 */
export function SelfReset(serverURL: string, uid: number, password: string): $CancellablePromise<[boolean, string, string]> {
    return $Call.ByID(1029676053, serverURL, uid, password);
}
